import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ReduxProvider from "@/lib/redux/ReduxProvider";
import { SearchProvider } from "@/context/SearchContext";
// import { ProductTrackingProvider } from "@/context/ProductTrackingContext";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bazaar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ReduxProvider>
            <SearchProvider>
              {/* <ProductTrackingProvider> */}
              {children}
              <Toaster
                position="top-center"
                closeButton
                toastOptions={{
                  style: {
                    color: "white",
                  },
                  classNames: {
                    success: "!bg-green-600 text-white border-0",
                    error: "!bg-red-600 text-white border-0",
                    info: "!bg-blue-600 text-white border-0",
                    warning: "!bg-amber-600 text-white border-0",
                    loading: "!bg-gray-700 text-white border-0",

                    toast: "text-white group",
                    title: "text-white font-semibold",
                    description: "text-white/90",

                    actionButton: "bg-white text-green-600 hover:bg-white/90",
                    cancelButton: "bg-gray-300 text-gray-700 hover:bg-gray-400",

                    closeButton:
                      "!bg-gray-900 hover:!bg-black text-white border-0 left-auto",

                    icon: "text-white",
                  },
                }}
              />

              {/* </ProductTrackingProvider> */}
            </SearchProvider>
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
