import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ReduxProvider from "@/lib/redux/ReduxProvider";
import { SearchProvider } from "@/context/SearchContext";
import { ProductTrackingProvider } from "@/context/ProductTrackingContext";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bazaar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ReduxProvider>
            <SearchProvider>
              <ProductTrackingProvider>
                {children}
                <Toaster position="top-center" richColors />
              </ProductTrackingProvider>
            </SearchProvider>
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
