import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ReduxProvider from "@/lib/redux/ReduxProvider";
import { SearchProvider } from "@/context/SearchContext";
// import { ProductTrackingProvider } from "@/context/ProductTrackingContext";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bazaar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ReduxProvider>
            <SearchProvider>
              {/* <ProductTrackingProvider> */}
              {children}
              <Toaster
                position="top-center"
                richColors
                closeButton
                toastOptions={{
                  classNames: {
                    success:
                      "bg-green-600 text-white border border-green-700 shadow-lg",
                    error:
                      "bg-red-600 text-white border border-red-700 shadow-lg",
                    loading:
                      "bg-blue-600 text-white border border-blue-700 shadow-lg",
                    info: "bg-slate-800 text-white border border-slate-700 shadow-lg",
                  },
                }}
              />

              {/* </ProductTrackingProvider> */}
            </SearchProvider>
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
